name: Trigger Weekly Scan

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger weeklyscan
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.WEEKLYSCAN_TOKEN }}" \
            https://api.github.com/repos/premchandoffice/weeklyscan/dispatches \
            -d '{
              "event_type":"run-sbom-scan",
              "client_payload":{
                "repository":"'"${GITHUB_REPOSITORY}"'",
                "clone_url":"'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"'",
                "branch":"'"${GITHUB_REF_NAME}"'",
                "sha":"'"${GITHUB_SHA}"'"
              }
            }'
